aliases set
VictorMoya07/react-native-training-base pull request #2
Opened 2022-08-09 17:40 UTC by VictorMoya07

## Summary
Se realiza el seteo de las alias del proyecto
[Change!] Describe your feature, problems you had, notes, improvements and others.

## Screenshots

[Change!] Show the screenshots of the views you modified.

### Android

#### Galaxy S (or similar)

#### Pixel 2/3 (or similar)

#### Pixel 3XL (or similar)

### iOS

#### iPhone SE (or similar)

#### iPhone 6/7/8 (or similar)

#### iPhone 11/12 Base/Pro/Pro Max (or similar)

## Trello Card

[Change!] Link to the associated Trello card.

2022-08-09 20:08 UTC, guidoprinc requested changes

2022-08-09 20:08 UTC, guidoprinc commented on wbooks/babel.config.js
> +          '@interfaces': './src/interface',
wouldn't it be `src/interfaces`?

2022-08-09 20:08 UTC, guidoprinc commented on wbooks/tsconfig.json
> +      "@interfaces/*": ["src/interface"],
`src/interfaces`

2022-08-09 20:16 UTC, VictorMoya07 commented on wbooks/tsconfig.json
> +      "@interfaces/*": ["src/interface"],
Change added

2022-08-10 13:05 UTC, guidoprinc approved these changes

2022-08-10 13:18 UTC, merged